### ISSUE TITLE
Broken / German Lobbying Meetings Dashboard

### ISSUE THREAD

**Issue by nelsonmau** [adilyalcin/Keshif#107]
German Lobbying Meetings Dashboard seems broken
http://keshif.me/demo/german_lobbying

It does not work in loading data. Log report: Cannot load data(Request timed out)

**Comment by adilyalcin** [comment]
Thanks @nelsonmau.

It might be a temporary problem on loading the data from the Google Sheet. It's not a small data. On my computer, the data could be loaded now. 

Can you try again and let me know if the issue is still there?

<img width="1273" alt="screen shot 2015-12-27 at 9 02 48 am" src="https://cloud.githubusercontent.com/assets/2327953/12010542/a2bb1be8-ac78-11e5-8262-9054a2ee5355.png">

**Comment by aborruso** [comment]
@nelsonmau the same for me

**Comment by nelsonmau** [comment]
Got it! 
The sheet _1B0vjide7zhHRjI2VVc_RF1-2rfoF_8AXl-7h7BvBkv8_ seems in "not published" status, authorization is required.  @adilyalcin could you be so kind to check it on GDrive?
Tnx a lot!

**Comment by adilyalcin** [comment]
The Google Sheet was private. Sorry, my mistake!

**Comment by nelsonmau** [comment]
Yep, just worked after refresh! thank you very much! :)

**Comment by adilyalcin** [comment]
Closing the issue now. Thanks for letting me know!
