### ISSUE TITLE
AggreSet Pane Width and Summary Card

### ISSUE THREAD

**Issue by hydrosquall** [adilyalcin/Keshif#146]
Hi Adil,

I saw the demo for AggreSet on Youtube, and was really excited to try it out! Unfortunately, it seems that the demo is imposing a max-width on the layout of ~850 pixels. Additionally, when I click the "show pair comparisons" pane, I can't seem to locate an option to resize or drag this summary card around. Perhaps I'm having difficulty finding the options to toggle these things, but if not would it be possible to copy the max-screensize and summary card capabilities of the main Keshif tool to AggreSet as well?

Thanks so much! I think this is a really cool tool :)

**Comment by adilyalcin** [comment]
Hi @hydrosquall,

Thanks for your interest and your message!

AggreSet matrix is now integrated with Keshif. Any time you have a multi-valued categorical data, clicking on the "tags" icon on the upper right corner will open the matrix view right next to the categories. The matrix is closely integrated with the category list, so they best work together. 

The matrix height is based on the height of the category list, and the width cannot exceed about the same height (since it is diagonal). To have more space for the matrix, close any other summaries within the same panel of the categorical summary. You may reposition the categories to another panel or change order within the summary by enabling authoring mode and drag-and-drop on the header. I will keep improving the documentation and how-to's, but for now the 5-min video should be useful for the basics of Keshif :: https://www.youtube.com/watch?v=3Hmvms-1grU

I hope this helps,

PS. There's a new Keshif maillist for such questions : https://groups.google.com/forum/#!forum/keshif
