### ISSUE TITLE
Error 502 on ECommerce demo on website

### ISSUE THREAD

**Issue by gavishgulati** [adilyalcin/Keshif#161]
Hello,
Unable to parse JSON when you try to load E-commerce chart from the given demos.

**Comment by adilyalcin** [comment]
I believe the issue was temporary. I experienced the same error that you did first, but then after a minute, the data could be loaded. The source JSON file is hosted at Google Drive, and Google was returning an error. 

I'm closing the issue for now. If you see the problem again, please let me know.
